### ISSUE TITLE
Other implementations of Landau-Vishkin

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [lh3/lv89#1]
Hej,

I came across this repo when looking for an implementation of the Landau-Vishkin algorithm. I'd like to compare my own work-in-progress algorithm to it, and since WFA is more general, a dedicated implementation for gap-linear or unit costs would be nice.

Are you aware of any other implementations? Or is the lack of them the reason you started this project? Are you planning to publish a paper based on this code that could be cited at some point?

Thanks!

**Comment by lh3** [comment]
LV89 will become much more complex even for linear gap penalty. Once we implement linear gap, affine gap will be fairly similar, which would be WFA. I have no plan to implement linear gap.

> since WFA is more general, a dedicated implementation for gap-linear or unit costs would be nice.

WFA2 now supports linear gap and edit distance. You can compare your implementation to that.

> Are you aware of any other implementations?

There are plenty of implementations if you google, but most of these are probably not efficient.

> Are you planning to publish a paper based on this code that could be cited at some point?

No. This is only a toy project. I don't mind if you cite the code or not. If you want to cite, you may cite the github link.
