### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [lh3/lv89#2]
```
// filter out diagonals that are unlikely to reach a better alignment than the current best. Only applicable to global alignment. This is not an approximation.
static inline void wf_prune_global(int32_t tl, int32_t ql, int32_t *st, int32_t *en, const wf_diag_t *b)
```

Looking at this function, this seems to be the approximation/reduction explained in section 4.2 if the WFA paper. However, your comment 'this is not an approximation' sounds like it preserves optimality of the alignment. 

What am I missing?

**Comment by lh3** [comment]
> this seems to be the approximation/reduction explained in section 4.2 if the WFA paper.

No, it is not. The WFA adaptive is a heuristic. This is an exact solution, though it often has no effect.

**Comment by RagnarGrootKoerkamp** [comment]
In that case, could you explain the filtering you do here? The comment says 'unlikely' but for this to be an exact filtering step it should be 'impossible' instead.

**Comment by lh3** [comment]
> The comment says 'unlikely' but for this to be an exact filtering step it should be 'impossible' instead.

The comment already says this is an exact solution. Feel free to change "unlikely" to "impossible".

> could you explain the filtering you do here?

I believe this is a very old strategy. For two strings of l1 and l2 in length respectively, the edit distance must be within [abs(l1-l2), max(l1,l2)]. In the middle of DP, you can estimate the max possible edit distance *D* without looking at substrings. Then you can discard cells that definitely can't reach the end within *D* in the best scenario.
