### ISSUE TITLE
[Question] Experimental setup information

### ISSUE THREAD

**Issue by smarco** [lh3/lv89#3]
Hi,

If possible, I would like to know the machine/core/architecture used for the experimentation presented on the README.

Thanks in advance,

**Comment by lh3** [comment]
Looking back at my experiment, I realized that I was not doing a comparison fair to WFA2. I will update README later.

Anyway, I was compiling WFA2-lib on an AMD CPU with gcc-4.8.5 from CentOS7. I was running all implementations on Xeon 4116. The OS is again CentOS7. Note that AMD doesn't have AVX512 but the Xeon CPU has. Perhaps WFA2-lib may get faster if I compile it on the Xeon.
