### ISSUE TITLE
Differences between Ukkonen and Landau-Vishkin

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [lh3/lv89#4]
You write in the readme that the presentation in Landau-Vishkin'89 is closer to modern one than the one from Ukkonen'85, but after some reading I've actually come to the opposite conclusion, so I'm wondering what I'm missing:

- LV finds all occurences of a pattern in a text, while you do global alignment.
- LV 'only' introduces the suffix-tree speedup for constant time extending, which you don't seem to use.
- The recursion presented in Ukkonen and LV otherwise looks the same to me.

**Comment by lh3** [comment]
You are correct. I read the Ukkonen paper but overlooked equation 10, which is basically the serial algorithm in LV89.

**Comment by RagnarGrootKoerkamp** [comment]
Could you update the readme (and rename the repo?) to prevent future confusion?

**Comment by lh3** [comment]
I have added a note to README and am going to archive this repo. Thanks for the correction.
